# Generated by Django 3.2.5 on 2021-07-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='image',
        ),
    ]
