# Generated by Django 3.2.5 on 2021-07-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210728_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
